### ISSUE TITLE
Change every XX seconds stuck at 60

### ISSUE THREAD

**Issue by bkcberry** [mrworf/photoframe#1]
I'm trying to decrease the amount of time each image is displayed but it's stuck at 60

**Comment by bkcberry** [comment]
at least 30

**Comment by mrworf** [comment]
Oki, well, I can change so it goes lower, but keep in mind that eventually you'll hit a hard limit based on the time it takes to download and prep the next image (typically around 10s on a RPi3). 

I'll do the change tonight and if you're using the image, it should self update at 3:15am

**Comment by mrworf** [comment]
Actually, there's a bug 😸 so the setting isn't saved. Sorry, will fix that AND the limit 😁

**Comment by mrworf** [comment]
If you pull (or login and run the update script, you'll get the fix

**Comment by mrworf** [comment]
And to answer @bkcberry 's question about minimum, it didn't make sense to me from either bandwidth usage or time to see the image 😄  but to each their own. It now does as low as 1s if your hardware can keep up. But it does show a warning at <20s since otherwise people will file bugs on it not keeping the requested time 😉

**Comment by bkcberry** [comment]
thanks :-)
