### ISSUE TITLE
Only ~10% of photos displaying

### ISSUE THREAD

**Issue by Braydon16** [mrworf/photoframe#108]
Hello,

First off we love your photo frame program!  It's been super easy to setup and use.  However, we have noticed that the same set of about 300-400 pictures keep being displayed without any new pictures.  We have a shared album on google photos that has over 4000 images, but it seems only a small section of photos from the beginning of the album are downloaded and displayed. 

Is there a max album size?  Is it an issue that my account on the photo frame is not the owner of the album and only a contributor?  

Thanks for any help!

Log file:
[debug.html.pdf](https://github.com/mrworf/photoframe/files/3474941/debug.html.pdf)

**Comment by mrworf** [comment]
Currently it's limiting the amount of photos to the last 1000. The goal 
is to have this configurable, but since we've been doing a remodel for 
the last 1.5 years, the last 6 months I have had a difficult time to 
find time to work on these improvements. I should get to this in the 
next month or two since we finally are starting to get our house back 
together again :)

If you don't want to wait, you can modify the source yourself (depending 
on how you feel about getting down and dirty ;)) by editing the 
following line:

https://github.com/mrworf/photoframe/blob/master/services/svc_googlephotos.py#L261

Change that from 1000 to any number you want, even if you specify a too 
high number, it will automatically stop once there are no photos to 
fetch.

CAVEAT! It stores all the data in ram, so depending on your setup, you 
may or may not run out of memory by doing this (for example if you're 
running a Pi Zero Wireless)

Let me know how it works if you decide to make this change.

**Comment by Braydon16** [comment]
Thank you for the super quick and informative reply!  I went ahead and updated the max images to 4000.  I'll report back with how my raspberry pi 3 B+ handles it.  Good luck with finishing up the remodel!

**Comment by Braydon16** [comment]
So far so good!  I check the memory usage before changing the max pictures to 4000.  It was at about 52M used.  Seems to be hovering around 95-100M after the change.  Time will tell.
![image](https://user-images.githubusercontent.com/648345/62710229-2eaf4100-b9b4-11e9-9ba3-75255fb0456e.png)

**Comment by mrworf** [comment]
How is it going? Still going strong?

**Comment by Braydon16** [comment]
Yes, still working great!  We did come back from a weekend away and it was stuck on the black screen.  Not sure if this was related to a memory issue or a power outage.  A reboot brought it back up and has been working ever since, about 3 weeks straight now.

**Comment by mrworf** [comment]
Sounds promising. Hoping to have the UI options per service setup in the coming months so this can be configured as needed.

**Comment by mrworf** [comment]
Closing this issue since the lack of updates indicates (to me) that things are working.

**Comment by Braydon16** [comment]
It's been working great!!!  Absolutely no issues to report. We now have two
albums syncing.  One with over 4000 photos and the other ~500.

Thanks,
Braydon
