### ISSUE TITLE
Zoom instead of black bars when borders too small

### ISSUE THREAD

**Issue by mrworf** [mrworf/photoframe#11]
When the borders would be too small when framing the image, it should zoom the image to fill the display instead of allowing black borders to remain.

**Comment by spirograf** [comment]
Not directly related to this issue, but is it possible to make an option to flip the display to portrait mode? It's possible to set the display_rotate=1 (or 3), but that doesn't affect photoframe as it continues to show the photos in landscape.

**Comment by mrworf** [comment]
@spirograf are you sure it's rotated? Easiest way to check is to connect a keyboard and hit ALT-F2 and hit enter a few times. This should show you a console login. I know someone else tried rotating it up-side-down and the config.txt file is very picky with the syntax, any spaces on that line between the equal sign will render the option disabled.

**Comment by Snille** [comment]
> Not directly related to this issue, but is it possible to make an option to flip the display to portrait mode? It's possible to set the display_rotate=1 (or 3), but that doesn't affect photoframe as it continues to show the photos in landscape.

This is now fixed. :) If you update it should be fixed. It's working for me at least. See: #25 
Works great!

**Comment by Snille** [comment]
@mrworf Regarding the "zoom", maybe you could set a "tag" like: #zoom (zoom until screen is full on any axis), #vzoom (zoom using the vertical as primary) or #hzoom (zoom using horizontal at primary) on the picture when you want it to be "zoomed", that way we can still have "small" pictures coming up in the slideshow without zooming it... Just a thought. :)

**Comment by mrworf** [comment]
Actually, it always zooms to maximize one of the dimensions and then places a blured image behind to cover the extra space, but in some cases, the space is too small, this is what I intended to fix. But I'll probably end up making it configurable if you don't like it :)

**Comment by Snille** [comment]
Configurable is the way to go! :)

And yes, I do see that my landscape frames are "filling" the leftover space with a blurred version of the picture, and I do like that feature. However, the portrait frames does not fill, see the picture.

What I meant with my earlier comment was that it would be nice if I could decide (per picture) the "zoom" behavior. In the picture for example I would like to have it zoomed in to the "horizontal" edges of the picture instead of the "vertical" as it's doing now. This would of course "cut" parts of the vertical edges. :) 

So basically 4 "modes" could be definable with "tags" on the picture. The default (no tag) being the current way of zoom (but with working fill on the portrait frames as well of course)... :)
#vzoom = Zoom the picture to the vertical edges.
#hzoom = Zoom the picture to the horizontal edges. 
#fzoom = Full zoom, the picture is zoomed so no black borders are visible on any sides. 
And no tags, default (current) behavior. :)

![image](https://user-images.githubusercontent.com/1011699/50373069-8c377e80-05d9-11e9-984b-f45bf6601a36.png)

Merry Christmas! 
Best regards Erik

**Comment by mrworf** [comment]
This has been partially implemented. Per image control of this behavior will probably not come in the near future since it's tricky to support in a generic way, especially since the goal is to add more photo providers.

**Comment by Snille** [comment]
I think I noticed on my "Portrait frame" that the left and right edges where now working (when the picture where "too tall", so that part works now. :) The "zoom / picture" It's not a "need to have" feature of course, I was just brainstorming. :) Maybe you could do it by frame instead? That's probably easier done? Same options but you set it on the frame (in the WebUI). What I miss the most is a "zoom-to-fill" function". Basically zoom in until there are no black edges on any side. :)

**Comment by mrworf** [comment]
You're in luck, you may already have it or a force update will give you what you ask
![image](https://user-images.githubusercontent.com/1848354/50565783-49675c00-0ce7-11e9-8804-25378cfbd37d.png)

**Comment by mrworf** [comment]
I'm going to close this one now since photoframe now has the options I had planned. Please feel free to open an issue if it doesn't work or you have suggestions.
