### ISSUE TITLE
Shutdown and restart via GPIO...

### ISSUE THREAD

**Issue by Snille** [mrworf/photoframe#129]
I'm giving away two frames to my parents, I want them to be able to turn off and on the frame in a good way. I have done this before on other PI-Projects and it works.

The "turn on" pin is usually GPIO number 3 (momentary switch on pin 5 and 6 will do it). But when setting that in the config, it does not work (for turn off).

The suggested GPIO number does not work for me to turn the frame on (if it's been turned off and the power has not been cut). And I also found that even if I set the button on the suggested GPIO (a momentary switch on pin 37 and 39) it's not really responding "quickly" to the button when pressing it, I got it to turn off sometimes, but not always.

I resorted to this guide to fix it: https://howchoo.com/g/mwnlytk3zmm/how-to-add-a-power-button-to-your-raspberry-pi

Maybe you can import it in to the frame in the future, it's really just two scripts... :)
Or maybe I'm doing something wrong in the first place?

Best regards Erik

**Comment by mrworf** [comment]
That's code I wrote ages ago and never ended up using myself, so it may have worked, but it might have broken over time. And funny story, it's based off an older version of that article 😸 

Anyway, I'll look into it because it should have worked by default. Thanks for letting me know.

**Comment by pitaru** [comment]
I am facing a similar issue:
The momentary switch I use to trigger the on/off on the frame used to work on a frame I made around spring. Even that one stopped responding to the push of the button. By burning a new SD card, the button will work one time to turn it off, one time to turn it back on, but after that the button is unresponsive.

**Comment by mrworf** [comment]
Hmm... odd, hopefully I'll have some time this weekend to test this on my own device.

**Comment by pitaru** [comment]
Under the issues tab on the project page on github there is a user who
posted the working solution. The button now works as expected. With the
latest image on the releases page, the button would not work. I tested it
on 2 separate RPI 3B+s and a 3A+ on a number of sd cards and usb sticks

**Comment by mrworf** [comment]
So I took time to investigate what happened. GPIO 26 did work (pin 37) but it wasn't being pull down, so it could at times behave flaky. At some point it seems to have allowed you to wake the RPi from any GPIO connected to the BCM, but that could just be my foggy brain. 

ANYWAY, the following has been done:
- Default has changed from GPIO 26 to GPIO 3 to make off/on behavior work
- Pull up has been enabled, making sure GPIO 3 doesn't float (bad for detecting ones and zeros)
- Language has changed somewhat to avoid PIN and also to specify GPIO 3
- Testing with display hat (waveshare 3.5b) shows no negative impact of using GPIO 3
- Bug in the refactor caused settings to be used before they were loaded, causing GPIO 26 to always be used even if UI said GPIO 3

These changes are now pushed and should show up within 24hrs.

I do have concerns with I2C devices since they use the same GPIO so it may be necessary to disable GPIO control (simplest is to map it back to 26). I am working on a better power management system which will make it possible to select which methods that control power (including motion! woho).

Let me know how it works out once it's been updated.

**Comment by Snille** [comment]
I'v got the update at least. Because I already have the "power off" script in the background, I have not tested the new GPIO (power off / on) function.  But other then that, it's working here. :)

**Comment by mrworf** [comment]
Closing this issue, should this still be an issue, please open a new issue.
