### ISSUE TITLE
Blank Screen (no photo showing)

### ISSUE THREAD

**Issue by slphotoframe** [mrworf/photoframe#133]
Hello, I've encountered an issue where the photoframe is just displaying a blank screen after start up.  Would appreciate any help.  Thanks

[log.txt](https://github.com/mrworf/photoframe/files/3720964/log.txt)

![2019-10-12_132322](https://user-images.githubusercontent.com/56485539/66705433-850e6800-ecf4-11e9-8307-d63d233efc06.jpg)

![2019-10-12_133117](https://user-images.githubusercontent.com/56485539/66705438-93f51a80-ecf4-11e9-8972-804b2d5d430b.jpg)

**Comment by mrworf** [comment]
It looks like the JSON file containing the memory of shown images has been corrupted (since it's failing to parse that). I've added a check for that, so if you force an update, it should be able to correct itself. But you may want to make sure your RPi has sufficient power (not thunderbolt showing in the top right corner) because SD Card corruption will easily happen otherwise 😢

**Comment by slphotoframe** [comment]
I completed a force update by creating a file called forceupdate.txt on the BOOT partition but saw a 'no new version' show up in the log.  When I hit the 'force update' button I get the confirmation window but after that no update happens.  In the log at the moment I'm still seeing "ValueError: No JSON object could be decoded"
Can you advise on what I'm doing incorrectly?

**Comment by mrworf** [comment]
Force update, either via Web UI or SDCard boot partition accomplishes the same (just for future reference). It should however have solved the issue. Can you get a new log report and upload here so we can see what's going on?

**Comment by mrworf** [comment]
I MUST APOLOGIZE! I did the fix but it never got pushed, just pushed it now so another update should fix it.

Again, so sorry 😭

**Comment by slphotoframe** [comment]
The update was successful!  Thank you
FYI whenever I've clicked on the force update button in the UI, it hasn't worked for me. 
I'm curious, what would have caused the JSON to become corrupted?

**Comment by mrworf** [comment]
The error 32 comes from me using flask as the main web server instead of relying on tornado or equivalent. It is not a symptom of any real error (your browser just closed the connection).

The force update will get better shortly, it will actually let you know if an update is possible instead of blindly running and many times not having anything to update to (since it auto updates every night).

The most common reason for JSON to be corrupted are:
1. USB Power supply isn't enough (causing slow corruption over time)
2. Pulling the power at an inopportune moment
3. Bad SD card (old card which simply is worn out)

1 & 2 are the ones I've seen most. #3 happened to me on my 24" frame since I cheaped out and used an old 1gb sd card from a phone 😄
