### ISSUE TITLE
Expose rotation from config.txt

### ISSUE THREAD

**Issue by mrworf** [mrworf/photoframe#15]
display orientation (or rotation as it were) should be exposed as a drop-down box to simplify the life of anyone trying to run a non-standard orientation 😄

**Comment by shigadeyo** [comment]
Yes, please! I was going to add a Feature Request for something like this as I wanted to have two photo frames, one in landscape and one in portrait. 

It would also be ideal to also have an option to configure which pictures should be displayed (e.g.; portrait, landscape, all/any) on a particular frame so that it would auto-filter the pictures based on the desired orientation/rotation. This would eliminate the need for doing this via manual tagging and should also supersede any defined tags.

**Comment by mrworf** [comment]
That's a really good idea. Added it as separate issue #72
