### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by icemanguru** [mrworf/photoframe#152]
Hi Github members I am new to Github and would like to thank you guys for making the PhotoFrame project possible for many users. I am not a strong programmer myself but, I wanted to share some ideas. I am sorry if I have placed this in the wrong area. 

1. I know the limitation to 1,000 photos is the max. I wanted to know what happens if this was increased or is it possible to increase?

2. Are special effects able to be added in this program like ( Ken Burns Effect ect...)

3. Also I have seen on other desktop systems like older Apple OS system or even DAK board that  when they run a slide show it has a feature called collage. Where you can create a template and have small windows inside the template and are able to point to specific folders in each window and are able to have different photos change with different timing.

I am sorry since I am not a strong coder I am unable to contribute on this project but, I wanted to just provide helpful ideas to help this project flourish and grown.

Thank you for taking time to read my Ideas.

**Comment by mrworf** [comment]
Hi sorry for the late reply... but better late than never I guess :)

1. The limitation is due to where the index is stored and processed. The goal is to allow the user to configure this. 
2. Due to hardware used and the way it's done (no hardware acceleration) this is not likely
3. Would be nice, but tricky to implement in the current setup.

If you wouldn't mind, please create separate tickets for items 1 & 2 and prefix them with "FR: " so it's clear you're asking for new features. That way they're not forgotten. Closing this ticket now.
