### ISSUE TITLE
Works for a few days/weeks then blank screen 

### ISSUE THREAD

**Issue by mnkypshngbttns** [mrworf/photoframe#166]
using google photos as a source. works fine for a while (days/weeks) using schedule on/off then one day just has blank screen and cant login to interface anymore. I have to reflash and resetup SD card all over again. Tried a new SD card and even a new Pi still the same problem. Only thing I haven't redone from scratch is the google photos authority been using the same clientsecret file I generated from the beginning. Any ideas or how I can get logs when it happens again to see what is going on

**Comment by mrworf** [comment]
I've had this issue once too and it was because my power supply and/or USB cable wasn't letting enough power through. I would occasionally see the ⚡ symbol on screen but I never saw any side-effects. Until about two months later when I started getting all kinds of weird errors. This was only solved by doing a reinstall on the same SD card. After 2 incidents, my SD card actually failed completely. Now it's running with a 3A usb plug. 

Is this the same issue? I don't know, sounds like it though. 

However, as to the question, you have two options:

1) Using a virtual machine with Ubuntu/Mint/etc, read the SD card

2) Install Linux Reader (https://www.diskinternals.com/linux-reader/access-ext4-from-windows/)

Once you can access the card, you will find the linux system log under `/var/log/syslog` and it should have all the details.

Now, option 1 is the most reliable way of reading the SD card since it can also do a filesystem repair should it be needed, but it might be a bit more daunting if you don't have experience with linux and/or virtual machines.

Third option is to use etcher.io to generate a raw image of your SD card which I'd be happy to inspect to see if I can get the logs from it. But it goes without saying that you'll be sharing wifi password and any cached images. I don't have any interest in this, but I figure full disclosure of what the options mean is probably a good idea.

**Comment by mnkypshngbttns** [comment]
Thanks for your thoughts Henric. I will try a new power supply and cable as they have not been changed when i tried the new raspberry pi so it would make sense it is common to all problems. Will let you know how it goes. Cheers!

**Comment by Snille** [comment]
Hi all, I have actually had the same problem on two of my frames. I changed the PSU on both, one of them has been OK since then, but the other one is still giving a blank screen some times. I also noticed that the network stops responding, but the Pi is actually running. So if i push my "Power button" (connected to pin 26) the frame closes down. Then if I just restart it, it works again. This made me think, maybe it's the "network-stack/card/chip/firmware" that's actually the problem? I'm running 3 frames on RPi ZeroW:s and one on a RPi 3. But it's only one of the Zero:s that have this problem. I'm going to try to update the frimware on the Pi Zero (rpi-update). But, I'm this brings another problem... When trying to update, the "photo-frame-software" "uses" up all the network bandwidth and/or all CPU power (on a Zero, it's not much :) to change the picture. So the ssh-session (running the rpi-update) closes down. So, how do I "stop" the photo-frame-software for a while, to let the rpi-update run its course. Then when the PI reboots, all is well. :) Maybe there could be an option to "stop" the actual photo-frame-script (or just the slideshow) form the GUI? :)

**Comment by mrworf** [comment]
I see two solutions (that are easy to do right now)
1. Change the slideshow delay to an hour and initate update once a new image is shown
2. Run `service frame.service stop` from ssh to terminate the photoframe software

**Comment by Snille** [comment]
On all of my 4 frames, none of them have the service installed?... Maybe I missed a step in the installation?
Anyway, this is just a "test" to see if the firmware where the problem, I just figured what task (number) the frame-python-script where running and killed it. Then updated the firmware. I guess we will see in a week or so if the frame still blacks out. :)

If the service had been installed, that would have been a good way to go. :) Also, that may be a "way" to stop the script from the gui... But of course not be able to restart it again without a reboot... :)

**Comment by mrworf** [comment]
Typo on my end, `service frame status/stop/start` will work, I think `systemctl` requires the full filename. So you have it, I'm pretty sure.

As for stopping the photoframe from the UX... Like you said, causes issues because you cannot reboot without pulling power. Maybe a `suspend` option would make more sense, where the slideshow is halted (similar to what happens when using scheduling)

**Comment by Snille** [comment]
Ah, yes, "service frame" works. :) 
A UX "suspend" would be great!

**Comment by Snille** [comment]
Hmm... Nope, got a black screen this morning. :/ I'll switch the PSU once more to another type, to see if I have been unlucky. However I do not get the small "lightning" symbol in the top right corner (that usually indicate that the PI don't have enough power). The strange thing is that it's still running, just the network that's dead...

**Comment by mrworf** [comment]
Keep in mind that running with the ⚡ symbol over time can slowly corrupt the SD card, so while you don't get the indicator any more, you may already have errors on the SD card which cause drivers/kernel to misbehave. I had a SD card break because of this

**Comment by Snille** [comment]
Hm, may be the case, if it happens again, then I'll reinstall the frame on a new sd-card... :)

**Comment by mrworf** [comment]
Closing this ticket due to inactivity
