### ISSUE TITLE
Add web portal address to the FAQs, Wiki, or readme

### ISSUE THREAD

**Issue by bdhanoa** [mrworf/photoframe#190]
Please add the web portal address with port to the FAQ, Wiki, or Readme. 

Currently you have to dig thorough the internet to find out that the web interface address is the following

http://{ipaddress}:7777

**Comment by mrworf** [comment]
I'm confused. The portal address is unique for each network which is why the frame itself shows the correct URL once it has connected to you wifi. See step #8 on the README.md

**Comment by dadr** [comment]
I've only ever been confused when I wanted to figure out the portal address for a running system.  And as Henric said, the address is dynamic, so it's not going to be something that can just be documented.

**Comment by bdhanoa** [comment]
I should have noted that the port of the webportal is what we should document. It is static, :7777. 

I had a hard time determining the port for the web portal. It is not documented in the readme file.

You are right that the portal ip address is dynamic and depends on the local network and configuration etc.

**Comment by dadr** [comment]
That would be easy enough to document.   Henric - is there a strong reason not to just use port 80?  I don't think people are running other web servers on photofames.

**Comment by mrworf** [comment]
The reason was that as non-root you cannot use ports below 1024 but this is legacy, it runs as root. It can default to 80 and have a command line argument to override if needed (since I don't dev as root 😅 ). But I think a major change like that would need to be part of the other issue I replied to, where we discuss photoframe 2.0 #191 or it would confuse everyone else. Can certainly add port number to the README.md and put a note that rebooting your frame will also show the URL during countdown to start.

**Comment by bdhanoa** [comment]
Thank you very much!

This is an awesome project. 

Congratulations on your success. Thanks for your efforts and for sharing.

**Comment by dadr** [comment]
The python3 branch runs on port 80. (now)

**Comment by bdhanoa** [comment]
Thank you very much. That's a good solution.

**Comment by mrworf** [comment]
Added details about port 7777 in the README.md
