### ISSUE TITLE
Is the official touchscreen supported

### ISSUE THREAD

**Issue by bkcberry** [mrworf/photoframe#36]
I flashed the image on the releases page, put in my wifi creds.. it joins the network but nothing happens on the touchscreen or thru HDMI

**Comment by mrworf** [comment]
I need a bit more details, what Raspberry are you using, how is the display connected and how long did you wait? Initial boot can take a few minutes, longer on slower raspberries.

And I assume you've run other distributions on your setup? Like Raspbian or similar to confirm it works as expected?

**Comment by bkcberry** [comment]
Sorry, should have been more descriptive! I am using a pi3, the display is connected with a ribbon cable thru the touchscreen connection port (? Not sure what it's official name is). I can boot raspbian and the screen works as expected, so I did a manual install (without disabling any of the stuff to hide all the startup screens) just to see if that makes any difference.. and the setup and oauth process works but the only display option is "use HDMI only"

**Comment by bkcberry** [comment]
Well the screen is working now with the raspbian image, so i'm not sure what changed.

I know this is unrelated, but is the serviceapi branch functional? I switched over to it because i saw where you said elsewhere the old API is being discontinued, and it doesn't show any images. I was able to auth my account but it tells me no images found, or check album name, regardless of what search term i put in. Please and thanks

**Comment by mrworf** [comment]
I honestly haven't tested with the ribbon screen (don't have one) so that might be a reason, but I'm glad you got it working. If you can, please provide a link for the screen so I can add better support for it.

As for the serviceapi branch, it should work, BUT, there's an additional step to making it work. On console.developers.google.com you need to enable the api used, click on "Enable APIs and services" 
![image](https://user-images.githubusercontent.com/1848354/50413737-fd3b8980-07c5-11e9-900b-b14b74dea316.png)

On the new screen, search for photo and select "Photos Library API" 
![image](https://user-images.githubusercontent.com/1848354/50413751-15130d80-07c6-11e9-8b56-da5a6ea77e34.png)

Once you've enabled it, it takes about 5-10min for the change to propagate through google's system and then you should start seeing results.

One of the last steps I have on my todo is to catch this config error and provide a better hint (and then confirm that migration of existing frames work) and it should be pretty much ready for broader rolllout

**Comment by bkcberry** [comment]
Awesome, thanks!
