### ISSUE TITLE
Initial boot not working

### ISSUE THREAD

**Issue by luke88jones** [mrworf/photoframe#65]
I've followed the instructions and created the boot drive with the wifi details but when I start up the PI it just shows what looks like a very torn jagged white image. I've left the PI for an hour or so but nothing changes. I reformatted the SD card with Raspbian and that loaded up fine. Any ideas on what might be wrong?

**Comment by mrworf** [comment]
@luke88jones some more details would be handy 😄 Which RPi are you using, what display is connected (HDMI or otherwise). Sounds like you're running a display which is tricking the photoframe in regards to width/height so it renders an image which isn't the correct width.

**Comment by luke88jones** [comment]
Sorry, yes, of course. It's a RPi 3 B connected over HDMI. I'll give the manual instructions a go and see where I get to

**Comment by mrworf** [comment]
Did you get it running manually? Either way, I'd really like it if you could run raspbian on that setup and run the following and give me the output:

`sudo fbset -v`

Because the error you describe is simply a mismatch between photoframe's idea of your display vs actual display and I'd love to fix it for you 😄

**Comment by luke88jones** [comment]
I followed the steps to run it manually but on restart I received the same screen as I got from the original image. Below is a picture of what I'm seeing. I'll get the disk re-flashed and run the command you mentioned. 

![image](https://user-images.githubusercontent.com/1705416/52662677-bb44df00-2efc-11e9-9e68-11a97bf78272.png)

**Comment by luke88jones** [comment]
output is...
```
Opening frame buffer device `/dev/fb0`
Using current video mode from `/dev/fb0`

mode "1366x768"
    geometry 1366 768 1366 768 32
    timings 0 0 0 0 0 0 0
    rgba 8/16,8/8,8/0,8/24
endmode
```

**Comment by mrworf** [comment]
Any chance you can run `frame.py` with the `--debug` and send me the output? Like so:

`frame.py --debug >log.txt` 

You should be able to just download the project and run it from commandline

**Comment by luke88jones** [comment]
I started with a clean raspbian install, installed the deps as per the manual steps. Cloned the repo and run `frame.py` with `--debug`. This is all I got from the output...
```
2019-02-17 11:29:54,175 - INFO - No http-auth.json found, disabling http authentication
2019-02-17 11:29:55,347 - INFO - No SMB subsystem, color sensor unavailable
2019-02-17 11:29:55,349 - DEBUG - hourOn = 4, hourOff = 22
2019-02-17 11:29:55,350 - DEBUG - Powermode changed to 'none'
2019-02-17 11:30:18,355 - INFO - Starting presentation
```

**Comment by mrworf** [comment]
Sigh, I seem to have removed the display info at some point. Oh well, let me do some math and see if I can figure this out :)

**Comment by luke88jones** [comment]
😢 Let me know if you want me to run anything else. Thanks for your help with this!

**Comment by mrworf** [comment]
I think I might be on to something here... If it can't get resolution information, it will default to 1280x720 which is a tad short width wise from your 1366 and it would definitely cause that artifact.

Can you run `/opt/vc/bin/tvservice -m DMT` and `/opt/vc/bin/tvservice -m CEA`  and see what happens (you may need to be root for it to work).

If my guess is correct, nothing will be shown (you should see a list of resolutions).

**Comment by mrworf** [comment]
Also, please attached the output :)

**Comment by luke88jones** [comment]
Output from the first command is 
```
Group DMT has 13 modes:
           mode 4: 640x480 @ 60Hz 4:3, clock:25MHz progressive 
           mode 5: 640x480 @ 72Hz 4:3, clock:31MHz progressive 
           mode 6: 640x480 @ 75Hz 4:3, clock:31MHz progressive 
           mode 8: 800x600 @ 56Hz 4:3, clock:36MHz progressive 
           mode 9: 800x600 @ 60Hz 4:3, clock:40MHz progressive 
           mode 10: 800x600 @ 72Hz 4:3, clock:50MHz progressive 
           mode 11: 800x600 @ 75Hz 4:3, clock:49MHz progressive 
           mode 16: 1024x768 @ 60Hz 4:3, clock:65MHz progressive 
           mode 17: 1024x768 @ 70Hz 4:3, clock:75MHz progressive 
           mode 18: 1024x768 @ 75Hz 4:3, clock:78MHz progressive 
           mode 22: 1280x768 @ 60Hz 15:9, clock:68MHz progressive 
  (prefer) mode 81: 1366x768 @ 60Hz 16:9, clock:85MHz progressive 
           mode 85: 1280x720 @ 60Hz 16:9, clock:74MHz progressive 
```
Second is 
```
Group CEA has 15 modes:
           mode 1: 640x480 @ 60Hz 4:3, clock:25MHz progressive 
           mode 2: 720x480 @ 60Hz 4:3, clock:27MHz progressive 
           mode 3: 720x480 @ 60Hz 16:9, clock:27MHz progressive 
           mode 4: 1280x720 @ 60Hz 16:9, clock:74MHz progressive 
           mode 5: 1920x1080 @ 60Hz 16:9, clock:74MHz interlaced 
           mode 6: 720x480 @ 60Hz 4:3, clock:27MHz x2 interlaced 
           mode 7: 720x480 @ 60Hz 16:9, clock:27MHz x2 interlaced 
           mode 16: 1920x1080 @ 60Hz 16:9, clock:148MHz progressive 
           mode 17: 720x576 @ 50Hz 4:3, clock:27MHz progressive 
           mode 18: 720x576 @ 50Hz 16:9, clock:27MHz progressive 
           mode 19: 1280x720 @ 50Hz 16:9, clock:74MHz progressive 
           mode 20: 1920x1080 @ 50Hz 16:9, clock:74MHz interlaced 
           mode 21: 720x576 @ 50Hz 4:3, clock:27MHz x2 interlaced 
           mode 22: 720x576 @ 50Hz 16:9, clock:27MHz x2 interlaced 
  (native) mode 31: 1920x1080 @ 50Hz 16:9, clock:148MHz progressive
```

**Comment by mrworf** [comment]
Hmm, when you ran `frame.py --debug`, you had run it once before, right? Because some hints are missing from the log output. If you delete the `/root/photoframe_config` folder and then run the debug again, there should be a line saying something like `No display settings, using ....` which should help me understand why things go bonkers :)

**Comment by luke88jones** [comment]
Sorry for the slow reply. You're correct! Just run again and I get the message you mentioned
```
2019-02-27 17:44:19,862 - INFO - No http-auth.json found, disabling http authentication
2019-02-27 17:44:19,921 - INFO - No display settings, using: {'3d_modes': [], 'width': 1366, 'rate': 60, 'code': 81, 'mode': 'DMT', 'scan': 'p', 'aspect_ratio': '', 'reverse': True, 'depth': 32, 'height': 768}
2019-02-27 17:44:22,379 - INFO - No SMB subsystem, color sensor unavailable
2019-02-27 17:44:22,382 - DEBUG - hourOn = 4, hourOff = 22
2019-02-27 17:44:22,383 - DEBUG - Powermode changed to 'none'
2019-02-27 17:44:45,974 - INFO - Starting presentation
```

**Comment by mrworf** [comment]
I haven't forgotten about you 😄 work just got very busy which has been limiting my time to work on projects (drained when I get home).

Something about this just doesn't make sense. The frame clearly says it's picking mode 81, which is the 1366x768 mode. This is matches what fbset says you're running.

It's quite clear from the screenshot that the images sent to the framebuffer seem to lack pixels on each row (since each pixel line is offset towards the left). Question is just why since fbset says we don't need more (sometimes resolutions require padding which isn't visible).

Have you manually edited the config.txt file? If so, could you post it here? If not, then let's not bother 😄 

I'll try and do an update this week which will cause debug mode to detail the settings sent to imagemagick which is used to present things to the screen.

In the meantime, try editing config.txt and add (or replace existing) the following:
```
hdmi_group=1
hdmi_mode=31
```

This should force your monitor into 1080p @ 50Hz which is the native resolution of it. See if this makes the frame work as expected.

Really appreciate your patience with this issue.

**Comment by luke88jones** [comment]
🎉 It works! Just setting up the auth for my Photos account but the screen render is fine now. Thanks for your help!

**Comment by mrworf** [comment]
Glad it worked out
