### ISSUE TITLE
Photoframe seem to reuse images sooner than expected

### ISSUE THREAD

**Issue by rafik24** [mrworf/photoframe#69]
Hi mrworf,

Currently the photoframe uses some randomness to display pictures from albums or latest, however I see many picture being displayed many time in short times intervals.

The idea of this feature would be to maintain a list of pictures displayed and set a time windows (let say a week) to not display the same picture from an album twice even if the photoframe app restarts.

We could also think of persisting some kind of album hashes to detect changes and show the newly picture identifiers without the need to re-display previously displayed pictures. 

My current albums keyword setup:

latest
2018 - has about 5500 pics
2017 - has about 5500 pics
2016 - has about 5500 pics all the way to 2009 have about 500 pictures each

**Comment by mrworf** [comment]
This is how it works today:

1. Download latest 1000 pics (not configurable yet)
2. Randomly pick one
3. Hash URL (which is unique for the image) and compare to list of shown. If already shown, goto 2
4. Download and show image
5. Goto 2

This has a few drawbacks.... (as you've noticed)
1. It only uses 1000 images of however many you have available
2. It relies 100% on google not having the same image twice with different URL (not likely)
3. Any kind of reboot blanks the database of shown images
4. With the default duration of 1 minute showing and no scheduled OFF time, you'll cycle through all images in less than 24hrs (more like 16 2/3 hrs).

How to fix...
1. Will be fixed once you can configure the individual service providers. Reason for not "grabbing" all photos instead of the last 1000 is that you might have an album of 10000 photos or more which will be a bit too much with the current way it deals with getting the list of photos (it's held in memory)
2. I want to use pHash to guarantee an image is shown twice, even if just a different resolution
3. Solvable by adding a save/restore service to the raspbian image so it simply copies the temporary data to hard storage on shutdown and restores it on boot. I don't want to be writing constantly to SD card since that can easily wear it out or have it corrupt the sd card if power is cut.
4. Cannot really be solved by software

I intend to fix #1 fairly soon since I have other neat ideas for service providers but they will require the dynamic config UI. pHash depends a lot on performance. The save/restore shouldn't be too hard, but it will need some testing.

Hope this answers some of your questions/ideas.

**Comment by rafik24** [comment]
Hi mrworf,

Thank you for taking the time to look at this.

Looking forward to see the frame evolve :+1: 

I hope I will be able to help, I am starting to learn Python.

**Comment by terrylmc** [comment]
I think I am having a similar issue as outlined above with pictures repeating.   Our google photos has about 15 albums which I have added to the photo frame software.  Each album is based on a year and have about 2000-10000 pics.

Our frame turns off the display from 10pm to 6am, does this count as a reboot like you mention above?

It seems we see the same pics almost every day around the same time, so I am wondering is there any way to increase the randomization to make sure it is pulling from all the albums with have listed, and not just the latest photos?   It does seem that the random pictures are coming across our albums as we see old pics and new that are in different albums.

Is there a setting to help with any of this?  

It would be great if there was some way it cycled through all the pictures before repeating any of them.

Thank you for the time you have put into this project.

**Comment by mrworf** [comment]
@terrylmc No, turning of the display doesn't count as reboot. All "memory" (if you will) is saved in `/tmp/` so only a true reboot would erase the known shown images. It reinitializes the random generator every day it starts, and then it randomly selects and album and randomly select a photo from said album. If image has been shown, then it picks a new photo from the album until it runs out or until it finds one it can show.

One thing that may cause you grief is if the images are in a format which the photoframe cannot interpret, such as the new fancy format used by the new iOS versions (HEIF). Imagemagick for ARM doesn't yet have the support (at least not a month or two ago when I checked) and that may cause it to skip a lot of photos. So if you only have 100 of the 1000 which are non-HEIF, you may end up with this odd scenario.

It will cycle through ALL photos from ALL albums before restarting. Only when the fetcher fails to get any photo should it restart from the top.

Try running it in debug mode and looking at logs and see if there's anything odd going on (like lots of unsupported formats and such).

**Comment by mrworf** [comment]
@leogaube improved the randomizer for photos which may work better now. Please keep an eye on it and let me know if you see an improvement.

**Comment by terrylmc** [comment]
Thank you.

**Comment by mrworf** [comment]
Closing this since there was a bug in how I cached google photo urls causing refetching within 30min (on average) which was wrong.
