### ISSUE TITLE
Google photos no longer syncing to google drive folder

### ISSUE THREAD

**Issue by ceebu** [mrworf/photoframe#96]
Not an issue, but a question - with the recent change to google photos not syncing to the google drive folder, how would the photoframe work for newer pics?

https://www.blog.google/products/photos/simplifying-google-photos-and-google-drive/

**Comment by mrworf** [comment]
It will have no impact since photoframe uses the official google photos API these days :-) but I appreciate that you reached out.
On 7/1/2019 7:25:26 AM, ceebu <notifications@github.com> wrote:
Not an issue, but a question - with the recent change to google photos not syncing to the google drive folder, how would the photoframe work for newer pics?
https://www.blog.google/products/photos/simplifying-google-photos-and-google-drive/ [https://www.blog.google/products/photos/simplifying-google-photos-and-google-drive/]
